# Generated by Django 3.0.2 on 2020-01-21 07:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lekarze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wizyty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField()),
                ('godzina', models.TimeField(choices=[(datetime.time(8, 0), '08:00'), (datetime.time(8, 15), '08:15'), (datetime.time(8, 30), '08:30'), (datetime.time(8, 45), '08:45'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 15), '09:15'), (datetime.time(9, 30), '09:30'), (datetime.time(9, 45), '09:45'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 15), '10:15'), (datetime.time(10, 30), '10:30'), (datetime.time(10, 45), '10:45'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 15), '11:15'), (datetime.time(11, 30), '11:30'), (datetime.time(11, 45), '11:45'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 15), '12:15'), (datetime.time(12, 30), '12:30'), (datetime.time(12, 45), '12:45'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 15), '13:15'), (datetime.time(13, 30), '13:30'), (datetime.time(13, 45), '13:45'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 15), '14:15'), (datetime.time(14, 30), '14:30'), (datetime.time(14, 45), '14:45'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 15), '15:15'), (datetime.time(15, 30), '15:30'), (datetime.time(15, 45), '15:45')])),
                ('status', models.CharField(choices=[('Ocz', 'Oczekująca'), ('Odw', 'Odwołana'), ('Zak', 'Zakończona')], default='Oczekująca', max_length=20)),
                ('recepta', models.CharField(blank=True, max_length=200, null=True)),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lekarze.Lekarze')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
